//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseId { get; set; }
        public int UserId { get; set; }
        public int PouchId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Priority { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public int Status { get; set; }
    
        public virtual Pouch Pouch { get; set; }
        public virtual User User { get; set; }
    }
}
